[features]
seeds = true

[programs.localnet]
solace = "8FRYfiEcSPFuJd27jkKaPBwFCiXDFYrnfwqgH9JFjS2U"

[programs.testnet]
solace = "8FRYfiEcSPFuJd27jkKaPBwFCiXDFYrnfwqgH9JFjS2U"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "http://127.0.0.1:8899"
# cluster = "testnet"
wallet = "./wallet/id.json"

[scripts]
airdrop = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tmp/airdrop.ts"
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/autoApproveAndSolTransfer.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tmp/**/*.ts"
